### ISSUE TITLE
TypeError when using Transition (Auto Animate) in new Framer Desktop version 2020.31

### ISSUE THREAD

**Issue by roswithawallner** [tisho/Switch.framerfx#11]
TypeError: undefined is not an object (evaluating 'name.match')
  at http://127.0.0.1:5567/preview-next-external-library.html?highlights=0&darkMode=1&projectURL=http://127.0.0.1:4567&imageBaseURL=http://127.0.0.1:4567&libraryURL=http://127.0.0.1:4567/node_modules/framer/build/framer.debug.js:123783:13 (:0:0)

  at AutoAnimatedState (utils/utils.ts:121195:53)

  at renderWithHooks (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:16406:27)

  at updateFunctionComponent (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:18493:35)

  at callCallback (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:330:19)

  at dispatchEvent@[native code] (:0:0)

  at invokeGuardedCallbackDev (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:379:29)

  at invokeGuardedCallback (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:434:36)

  at beginWork$$1 (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:25926:28)

  at performUnitOfWork (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:24844:24)

  at workLoopSync (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:24817:39)

  at performSyncWorkOnRoot (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:24416:23)

  at performSyncWorkOnRoot@[native code] (:0:0)

  at http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:12345:32 (:0:0)

  at unstable_runWithPriority (http://127.0.0.1:5567/scripts/react/react.development.js:2975:24)

  at flushSyncCallbackQueueImpl (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:12340:24)

  at flushSyncCallbackQueue (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:12328:29)

  at scheduleUpdateOnFiber (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:23855:31)

  at dispatchAction (http://127.0.0.1:5567/scripts/react-dom/react-dom.development.js:17222:17)

  at dispatchAction@[native code] (:0:0)

  at http://127.0.0.1:5567/preview-next-without-library.js:1:1197864 (:0:0)

  at http://127.0.0.1:5567/preview-next-without-library.js:1:1199088 (:0:0)

  at asyncFunctionResume@[native code] (:0:0)

  at http://127.0.0.1:5567/preview-next-without-library.js:1:557296 (:0:0)

  at asyncFunctionResume@[native code] (:0:0)

  at promiseReactionJob@[native code] (:0:0)

**Comment by tisho** [comment]
Thanks for reporting. This is fixed in 1.24.0.
